version: "3.7"

services:
  #server:
    #build: .  #  parcours du projet
    #stdin_open: true  #donner ok
    #tty:  true #pour tenir le server actif
    #ports:
    ##  - "5500:5500" # dire a la porteur externe d entrer dans ma porte
    #depends_on:  # elle est dependente du serrver sql arcadia
    #  - db_arcadia 
    #volumes:
    #  - .:/code

  nginx:
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./php/:/var/www/html/

  php:
    build: ./php/
    expose:
      - 9000
    volumes:
      - ./php/:/var/www/html/
    environment:
      DB_PASSWORD: patrice
      DB_SECRET: ufhz56546argçrhqyqgsdnuhsb4545fqsu
      DB_CONNECTION: mysql:host=localhost;dbname=Zoo_arcadia;charset=utf8

  db_arcadia:
    image: mysql:5.7
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - C:/wamp64/www/ZOOARCARDIA2/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: Zoo_arcadia
      MYSQL_PASSWORD: patrice
      MYSQL_ROOT_PASSWORD: patrice
