version: "3"

services:

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile   #server in gnix
    depends_on:
      - db_arcadia
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    depends_on:
      - db_arcadia
    environment:
      DB_PASSWORD: patrice
      DB_SECRET: ufhz56546argçrhqyqgsdnuhsb4545fqsu
      DB_CONNECTION: mysql:host=db_arcadia;dbname=Zoo_arcadia;charset=utf8
    volumes:
      - .:/app/

  db_arcadia:
    image: mysql:5.7
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - C:/Users/temok/OneDrive/Desktop/git/ZOOARCARDIA2/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: Zoo_arcadia
      MYSQL_ROOT_PASSWORD: patrice
